SMS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('adminapp.urls')),
    path('studentapp/', include('studentapp.urls')),
    path('facultyapp/', include('facultyapp.urls')),


]

facultyapp/urls.py
from django.urls import path, include
from .import views
app_name='facultyapp'
urlpatterns=[
    path('FacultyHomePage', views.FacultyHomePage, name='FacultyHomePage'),
    path('add_course', views.add_course, name='add_course'),
    path('view_student_list', views.view_student_list, name='view_student_list'),
    path('post_marks', views.view_student_list, name='post_marks'),
    path('feedback/', views.submit_feedback, name='feedback'),
    path('feedback/list/', views.feedback_list, name='feedback_list'),
    path('qq', views.qq, name='post_marks'),

]

studentapp/urls.py
from django.urls import path, include
from . import views
app_name='studentapp'
urlpatterns= [
path('StudentHomePage', views.StudentHomePage,name='StudentHomePage'),
path('view_marks', views.view_marks, name='view_marks'),

]

templates/Navbar/FacultyNavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Rohith Vema</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg" style="background-color: #e3f2fd">
  <div class="container-fluid">
       <a class="navbar-brand" href="{% url 'htmlpage1' %}">SMS</a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'facultyapp:FacultyHomePage' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Python Extensions</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            DropDownBox
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'printpagecall' %}">Printer</a></li>
             <li><a class="dropdown-item" href="{% url 'exceptionpagecall' %}">ExceptionHandler</a></li>
             <li><a class="dropdown-item" href="{% url 'calculatorpagecall' %}">Calculator</a></li>
                          <li><a class="dropdown-item" href="{% url 'randompagecall' %}">OtpGenerator</a></li>
                          <li><a class="dropdown-item" href="{% url 'datetimepagecall' %}">Date and time</a></li>
                          <li><a class="dropdown-item" href="{% url 'add_task' %}">To-Do list</a></li>
                          <li><a class="dropdown-item" href="{% url 'facultyapp:add_course' %}">Add Course</a></li>
                          <li><a class="dropdown-item" href="{% url 'facultyapp:view_student_list' %}">Student List With Courses</a></li>
                          <li><a class="dropdown-item" href="{% url 'facultyapp:post_marks' %}">Post Marks</a></li>
                          <li><a class="dropdown-item" href="{% url 'add_student' %}">Add Student</a></li>
                          <li><a class="dropdown-item" href="{% url 'student_list' %}">Student List</a></li>

                          <li><a class="dropdown-item" href="{% url 'facultyapp:feedback_list' %}">Check feedback</a></li>
















            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">No Action</a></li>

          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"></a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
    <ul  class="navbar-nav ms-auto">
<li>
        {% if user.is_authenticated %}
        <li class="nav-item">
        <span class="nav-link">Welcome, {{ user.username }}</span>
    </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
        {% else %}
                <li class="nav-item">
          <a class="nav-link" href="{% url 'UserRegisterPageCall' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'UserLoginPageCall' %}">Login</a>
        </li>
        {% endif %}

 </li>

      </ul>
  </div>

</nav>
{% block body %}
{% endblock %}

</body>
</html>

templates/Navbar/StudentNavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Rohith Vema</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg" style="background-color: #e3f2fd">
  <div class="container-fluid">
       <a class="navbar-brand" href="{% url 'htmlpage1' %}">SMS</a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Python Extensions</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            DropDownBox
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'printpagecall' %}">Printer</a></li>
             <li><a class="dropdown-item" href="{% url 'exceptionpagecall' %}">ExceptionHandler</a></li>
             <li><a class="dropdown-item" href="{% url 'calculatorpagecall' %}">Calculator</a></li>
                          <li><a class="dropdown-item" href="{% url 'randompagecall' %}">OtpGenerator</a></li>
                          <li><a class="dropdown-item" href="{% url 'datetimepagecall' %}">Date and time</a></li>
                          <li><a class="dropdown-item" href="{% url 'add_task' %}">To-Do list</a></li>
                                        <li><a class="dropdown-item" href="{% url 'facultyapp:feedback' %}">Give feedback</a></li>
                                        <li><a class="dropdown-item" href="{% url 'studentapp:view_marks' %}">View Marks</a></li>










            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">No Action</a></li>

          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"></a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
    <ul  class="navbar-nav ms-auto">
<li>
        {% if user.is_authenticated %}
        <li class="nav-item">
        <span class="nav-link">Welcome, {{ user.username }}</span>
    </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
        {% else %}
                <li class="nav-item">
          <a class="nav-link" href="{% url 'UserRegisterPageCall' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'UserLoginPageCall' %}">Login</a>
        </li>
        {% endif %}

 </li>

      </ul>
  </div>

</nav>
{% block body %}
{% endblock %}

</body>
</html>

templates/Navbar/projectNavBar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Rohith Vema</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg" style="background-color: #e3f2fd">
  <div class="container-fluid">
       <a class="navbar-brand" href="{% url 'htmlpage1' %}">SMS</a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'htmlpage1' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Python Extensions</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            DropDownBox
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'printpagecall' %}">Printer</a></li>
             <li><a class="dropdown-item" href="{% url 'exceptionpagecall' %}">ExceptionHandler</a></li>
             <li><a class="dropdown-item" href="{% url 'calculatorpagecall' %}">Calculator</a></li>
                          <li><a class="dropdown-item" href="{% url 'randompagecall' %}">OtpGenerator</a></li>
                          <li><a class="dropdown-item" href="{% url 'datetimepagecall' %}">Date and time</a></li>
                          <li><a class="dropdown-item" href="{% url 'add_task' %}">To-Do list</a></li>











            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">No Action</a></li>

          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"></a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
    <ul  class="navbar-nav ms-auto">
<li>
        {% if user.is_authenticated %}
        <li class="nav-item">
        <span class="nav-link">Welcome, {{ user.username }}</span>
    </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
        {% else %}
                <li class="nav-item">
          <a class="nav-link" href="{% url 'UserRegisterPageCall' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'UserLoginPageCall' %}">Login</a>
        </li>
        {% endif %}

 </li>

      </ul>
  </div>
  
</nav>
{% block body %}
{% endblock %}

</body>
</html>